#!/usr/bin/env bash
# push.sh — Push each generated repo as an individual GitHub repository
#
# Usage:
#   scripts/push.sh                        # push all verified repos in generated/
#   scripts/push.sh crud-python-fastapi    # push one repo by name
#
# Env vars:
#   GH_ORG      — target GitHub org (required, or set --org flag)
#   GH_PRIVATE  — set to "true" to create private repos (default: public)
#   DRY_RUN     — set to "true" to print commands without executing
#
# Requires: git, gh CLI (authenticated)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GENERATED_DIR="$REPO_ROOT/generated"

# Allow --org flag as override
ORG="${GH_ORG:-}"
PRIVATE="${GH_PRIVATE:-false}"
DRY_RUN="${DRY_RUN:-false}"

# Parse --org flag
args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --org) ORG="$2"; shift 2 ;;
    --private) PRIVATE="true"; shift ;;
    --dry-run) DRY_RUN="true"; shift ;;
    *) args+=("$1"); shift ;;
  esac
done

if [[ -z "$ORG" ]]; then
  echo "Error: GitHub org required. Set GH_ORG env var or pass --org <org>" >&2
  exit 1
fi

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()   { echo -e "${GREEN}[push]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
error() { echo -e "${RED}[error]${NC} $*" >&2; }

if ! command -v gh &>/dev/null; then
  error "gh CLI not found. Install with: brew install gh && gh auth login"
  exit 1
fi

push_repo() {
  local repo_name="$1"
  local repo_path="$GENERATED_DIR/$repo_name"

  if [ ! -d "$repo_path" ]; then
    error "Directory not found: $repo_path"
    return 1
  fi

  log "Processing $repo_name"

  # Init git if needed
  if [ ! -d "$repo_path/.git" ]; then
    log "  Initializing git repo"
    if [ "$DRY_RUN" != "true" ]; then
      git -C "$repo_path" init -b main
      git -C "$repo_path" add .
      git -C "$repo_path" commit -m "Initial commit: $repo_name"
    else
      echo "  [dry-run] git init + add + commit in $repo_path"
    fi
  else
    if ! git -C "$repo_path" rev-parse HEAD &>/dev/null; then
      if [ "$DRY_RUN" != "true" ]; then
        git -C "$repo_path" add .
        git -C "$repo_path" commit -m "Initial commit: $repo_name"
      fi
    fi
    local current_branch
    current_branch=$(git -C "$repo_path" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
    if [ "$current_branch" != "main" ]; then
      if [ "$DRY_RUN" != "true" ]; then
        git -C "$repo_path" checkout -b main 2>/dev/null || git -C "$repo_path" checkout main
      fi
    fi
  fi

  local visibility_flag="--public"
  [ "$PRIVATE" = "true" ] && visibility_flag="--private"

  log "  Creating $ORG/$repo_name on GitHub"
  if [ "$DRY_RUN" = "true" ]; then
    echo "  [dry-run] gh repo create $ORG/$repo_name $visibility_flag"
    echo "  [dry-run] git push -u origin main"
  else
    gh repo create "$ORG/$repo_name" $visibility_flag \
      --description "Generated by repogen: $repo_name" 2>/dev/null \
      && log "  Created $ORG/$repo_name" \
      || warn "  Repo $ORG/$repo_name may already exist — continuing"

    local gh_token
    gh_token=$(gh auth token 2>/dev/null || true)
    local remote_url="https://github.com/$ORG/$repo_name.git"
    if [ -n "$gh_token" ]; then
      remote_url="https://x-access-token:${gh_token}@github.com/$ORG/$repo_name.git"
    fi

    if git -C "$repo_path" remote get-url origin &>/dev/null; then
      git -C "$repo_path" remote set-url origin "$remote_url"
    else
      git -C "$repo_path" remote add origin "$remote_url"
    fi

    log "  Pushing to https://github.com/$ORG/$repo_name"
    git -C "$repo_path" push -u origin main
  fi

  log "  Done: https://github.com/$ORG/$repo_name"
}

# Determine which repos to process
if [ ${#args[@]} -gt 0 ]; then
  for name in "${args[@]}"; do
    push_repo "$name"
  done
else
  # Default: push all verified repos from progress.yaml
  verified_repos=()
  if command -v python3 &>/dev/null && [ -f "$REPO_ROOT/progress.yaml" ]; then
    while IFS= read -r name; do
      verified_repos+=("$name")
    done < <(python3 -c "
import yaml
with open('$REPO_ROOT/progress.yaml') as f:
    data = yaml.safe_load(f) or {}
for name, info in data.get('repos', {}).items():
    if info.get('verified'):
        print(name)
" 2>/dev/null)
  fi

  if [ ${#verified_repos[@]} -eq 0 ]; then
    warn "No verified repos found in progress.yaml. Running repogen verify first is recommended."
    warn "To push all repos regardless, list them explicitly: scripts/push.sh <name1> <name2> ..."
    exit 0
  fi

  failed=()
  for name in "${verified_repos[@]}"; do
    push_repo "$name" || failed+=("$name")
  done

  if [ ${#failed[@]} -gt 0 ]; then
    error "Failed repos: ${failed[*]}"
    exit 1
  fi
fi

log "All done."
